### ISSUE TITLE
Make a new "setup-infracost" GH Action to allow more composablility

### ISSUE THREAD

**Issue by tim775** [infracost/infracost#1115]
### Make the GH Action more composable
Currently the infracost action runs the ‘scripts/ci/diff.sh’ bash script.  That  performs several steps: runs terraform, generates a diff, puts a comment on the pr.  Each of these could be exposed as individual steps making it easier to, for example, upload the diff as an artifact.

_Originally posted by @tim775 in https://github.com/infracost/infracost/discussions/1054#discussioncomment-1484100_

**Comment by darshan-thinknyx** [comment]
Uploading the values like **'previous cost'** and **'change in % of cost'** also as artifacts will help for further use.

**Comment by tim775** [comment]
Update: We now have an [infracost/actions](https://github.com/infracost/actions) repo with a setup action that can be used as 
```
   steps:
     ...
      - name: Setup Infracost
        uses: infracost/actions/setup@master
        with:
          api_key: ${{ secrets.INFRACOST_API_KEY }}
     ...
``` 
See the [README](https://github.com/infracost/actions#readme) for a complete example.  

Please treat this as experimental until we publish `infracost/actions@v1` to the GitHub marketplace!
