### ISSUE TITLE
In-built parsing of "+" or "-" value

### ISSUE THREAD

**Issue by IrmantasMarozas** [infracost/infracost#1153]
First of all, thanks for maintaining this, this is amazing, can't wait for Enterpise offers to become available!

I only had a couple of hours to play with this so far to integrate it into CI/CD pipelines but... It would be really cool way to use it as a "quality gate" rather than a reporting tool. ATM my plan is to parse the output and then compare it to "allowed difference" value to make it a quality gate, but it seems to be simple to implement an additional argument that would return exit code 0 or 1 or depending whether you are breaching your threshold or not.

i.e.

```
infracost diff --path prod.plan --allowed-max-increase 1000 --allowed-max-decrease 100

if cost increase is more than 1000 then return failure code
if cost decrease is above 100 then return a failure code
```

This could be handled in many different ways depending on how the tool is used, but it would make life easier.

Use case: I want to be notified/alerted/or even fail the pipeline if unexpected cost changes are detected in a change.

**Comment by alikhajeh1** [comment]
@IrmantasMarozas thanks! That's an awesome use-case :) What's the CI/CD pipeline you're using? We've been working on new set of GitHub Actions, see https://github.com/infracost/actions/ for our work-in-progress (we'll announce it soon). Specifically the "Thresholds" [example](https://github.com/infracost/actions/#examples) does what you're talking about. 

Our idea so far has been that the Infracost CLI JSON output can be used to experiment with thresholds or policies (even integration with OPA). We plan to support other CI/CD pipelines and create similar examples. We're also happy to receive community help with these :)

**Comment by IrmantasMarozas** [comment]
> What's the CI/CD pipeline you're using

Self-hosted GitLab. I was trying to use your examples from docs, but it didn't work, so I ended up with this:

```yaml
infracost:
  stage: infracost
  before_script:
    - cd $TF_ROOT
  script:
    - |
      os=$(uname | tr '[:upper:]' '[:lower:]')
      arch=$(uname -m | tr '[:upper:]' '[:lower:]' | sed -e s/x86_64/amd64/)
      echo "Downloading latest release of infracost-$os-$arch..."
      curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-$os-$arch.tar.gz | tar xz -C /usr/local/bin
      mv /usr/local/bin/infracost-$os-$arch /usr/local/bin/infracost
    - infracost breakdown --path dev.plan
    - infracost diff --path dev.plan
  cache:
    - key: "${CI_COMMIT_SHORT_SHA}_dev_terraform_plan"
      paths:
        - ${TF_ROOT}/dev.plan
    - key: "${CI_COMMIT_SHORT_SHA}_terraform_init"
      paths:
        - ${TF_ROOT}/.terraform/
      policy: pull
```
