### ISSUE TITLE
Azure DevOps "Manual" runs and GitHub PR comments

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1266]
Azure DevOps with GitHub pull requests has a mode where the `$BUILD_REASON=Manual`, but the pull request env vars are set. We should detect this in the new Azure DevOps integration and still post a pull request comment. At the moment, the diff.sh script fails with `Posting comment to Azure DevOps $BUILD_REASON is not supported, email hello@infracost.io for help`.

**Comment by alikhajeh1** [comment]
@vdmgolub / @aliscott is this already handled by the new [Azure DevOps extension](https://github.com/infracost/infracost-azure-devops)? If so, please close it

**Comment by vdmgolub** [comment]
@alikhajeh1 I think it's resolved, but let me double-check and I'll close it if it's working okay 👍

**Comment by vdmgolub** [comment]
Verified, running a pipeline manually using [InfracostTasks](https://marketplace.visualstudio.com/items?itemName=Infracost.infracost-tasks) and setting a GitHub PR number as an env var posts the comment. Here's an example how to do this:
```yaml
      - task: InfracostComment@0
        displayName: Post the comment
        inputs:
          githubToken: $(githubToken)
          path: /tmp/infracost.json
          behavior: update
        env:
          SYSTEM_PULLREQUEST_PULLREQUESTNUMBER: 5
```
