### ISSUE TITLE
[Feature Request] Config File Workspaces

### ISSUE THREAD

**Issue by stobias123** [infracost/infracost#1280]
Feature request to allow for workspaces as an array in the config file.

Each of my directories has multiple workspaces. So it becomes very verbose very quickly to add them.

Consider this

```yaml
projects:
  - path: terraform
    terraform_workspace: dev
  - path: api-foo/terraform
    terraform_workspace: dev
    terraform_plan_flags: --var helm_version=foo --var image_tag=foo
  - path: worker-foo/terraform
    terraform_workspace: dev
    terraform_plan_flags: --var helm_version=foo --var image_tag=foo
  - path: terraform
    terraform_workspace: prod
  - path: api-foo/terraform
    terraform_workspace: prod
    terraform_plan_flags: --var helm_version=foo --var image_tag=foo
  - path: worker-foo/terraform
    terraform_workspace: prod
    terraform_plan_flags: --var helm_version=foo --var image_tag=foo
```
    
vs proposed...

```yaml    
projects:
  - path: terraform
    terraform_workspaces:
      - dev
      - prod
  - path: api-foo/terraform
    terraform_workspace:
      - dev
      - prod
    terraform_plan_flags: --var helm_version=foo --var image_tag=foo
  - path: worker-foo/terraform
    terraform_workspace: 
      - dev
      - prod
    terraform_plan_flags: --var helm_version=foo --var image_tag=foo
```

**Comment by alikhajeh1** [comment]
Thanks @stobias123 - that looks simpler indeed!

Two quick questions:
1. Have you found the need to specify project names before? e.g. in pull request comment [summary table](https://github.com/infracost/actions/raw/master/.github/assets/screenshot.png), I think at the moment we use the project path and put the workspace in brackets so you'd see the following - is that ok or do you need the ability to override the name sometimes?
  terraform (dev)
  terraform (prod)
  api-foo/terraform (dev)
  api-foo/terraform (prod)

2. What do you think about having a per-directory config files? So `terraform/infracost.yaml` just includes the config for that dir; likewise for `api-foo/terraform/infracost.yaml` and `worker-foo/terraform/infracost.yaml`. You could then run `infracost breakdown --config-file "**/infracost.yaml"` at the top-level dir, and the CLI would find and combine the configs. You could also just run `infracost breakdown --config-file workers-foo/terraform` if you only want to see that dir's output.

**Comment by stobias123** [comment]
1. No project path is fine
2. IMO one file top level. If you need to specify paths via wildcard, I'd rather specify file paths (with wildcards) that contain tf in the config file rather than create a bunch of files. Managing tons of files becomes challenging.

So something like this rather than one file per sub project

```yaml
# $PROJECT_ROOT/infracost.yaml
projects:
  - path: terraform
     terraform_workspace:
      - dev 
      - prod
  - path: **/terraform
    terraform_workspaces:
      - dev
      - prod
  ```
