### ISSUE TITLE
Debugging config-file issues without INFRACOST_PARALLELISM=1

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1485]
Is it possible to log the project path that resulted in errors when running with config-file?

I have this [config-file](https://www.infracost.io/docs/features/config_file/):
```
version: 0.1
projects:
  - path: dev
    usage_file: dev/infracost-usage.yml
    env:
      AWS_PROFILE: dev
      AWS_ACCESS_KEY_ID: ${DEV_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${DEV_AWS_SECRET_ACCESS_KEY}
  - path: prod
    usage_file: prod/infracost-usage.yml
    env:
      AWS_PROFILE: prod
      AWS_ACCESS_KEY_ID: ${PROD_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${PROD_AWS_SECRET_ACCESS_KEY}
```

When I run `infracost breakdown --config-file infracost.yml`, the CLI errors without telling me which project path failed. I know I can re-run with `INFRACOST_PARALLELISM=1 ` to debug but it would be a much smoother developer experience if the error tells me which project path failed.

```
Running multiple projects in parallel, so log-level=info is enabled by default.
Run with INFRACOST_PARALLELISM=1 to disable parallelism to help debugging.

time="2022-03-22T22:30:02-07:00" level=info msg="Detected Terraform directory at prod"
time="2022-03-22T22:30:02-07:00" level=info msg="Detected Terraform directory at dev"
time="2022-03-22T22:30:02-07:00" level=info msg="Starting: Checking for cached plan..."
time="2022-03-22T22:30:02-07:00" level=info msg="Starting: Checking for cached plan..."
time="2022-03-22T22:30:02-07:00" level=info msg="Starting: Running terraform plan"
time="2022-03-22T22:30:02-07:00" level=info msg="Starting: Running terraform plan"

time="2022-03-22T22:30:23-07:00" level=info msg="Starting: Running terraform show"
time="2022-03-22T22:30:29-07:00" level=info msg="Starting: Extracting only cost-related params from terraform"
time="2022-03-22T22:30:29-07:00" level=info msg="Starting: Retrieving cloud prices to calculate costs"
Error: terraform plan failed: exit status 1

  Terraform command failed with:
    Error: Module version requirements have changed
      on ../modules/base/eks.tf line 18, in module "eks":
      18:   source          = "terraform-aws-modules/eks/aws"
    The version requirements have changed since this module was installed and the
    installed version (17.24.0) is no longer acceptable. Run "terraform init" to
    install all modules required by this configuration.

Try setting the --path to a Terraform plan JSON file. See https://infracost.io/troubleshoot for how to generate this.
```

### Note for community
Please 👍 if you'd like to upvote this or receive updates.
