### ISSUE TITLE
Terragrunt project appears multiple times in output

### ISSUE THREAD

**Issue by fellnerse** [infracost/infracost#1788]
When running the `diff` on our project we somehow get some projects multiple times in the output. You can see the result here: https://dashboard.infracost.io/share/evblu6q4e9kfgnegw0qbvz16krd3c1fl#1ed99956-4c8e-49d5-bc56-fe14c5e0ed75
i.e. the first one appears two times, apparently its matched somehow twice (the path is differently). Do you know how I could solve this? Maybe with the config file?
Thanks in advance!

**Comment by aliscott** [comment]
Thanks @fellnerse, I'll look into this today. Do you have the current command you are using to run Infracost?

**Comment by fellnerse** [comment]
here are parts of our azure pipeline:

```yaml
      - task: InfracostSetup@1
        inputs:
          apiKey: $(TERRACOST_API_KEY)
          version: "0.10.6"
          enableDashboard: true
      - bash: infracost breakdown --path=deployments --format=json --out-file=$(file_name)
        displayName: Generate Infracost cost estimate

      - publish: "$(file_name)"
        artifact: infracost-baseline
```
```yaml
      - task: InfracostSetup@1
        inputs:
          apiKey: $(TERRACOST_API_KEY)
          version: "0.10.6"
          enableDashboard: true
      - download: 'main-pipe' # this comes from pr.yaml resource section
        artifact: infracost-baseline # and this from the jobs.publish-baseline.yaml

        # Generate an Infracost diff and save it to a JSON file.
      - bash: |
          infracost diff --path=deployments \
          --format=json \
          --compare-to=$(Pipeline.Workspace)/main-pipe/infracost-baseline/infracost-baseline.json \
          --out-file=$(file_name)
        displayName: Generate Infracost diff

      - bash: |
          infracost comment azure-repos \
             --path $(file_name) \
             --azure-access-token $(System.AccessToken) \
             --pull-request $(System.PullRequest.PullRequestId) \
             --repo-url $(Build.Repository.Uri) \
             --behavior delete-and-new
        displayName: Post Infracost comment
```
