### ISSUE TITLE
Tagging Infracost projects

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1807]
# Problem

Users can currently [override the default project names](https://www.infracost.io/docs/infracost_cloud/key_concepts/#projects) when the Infracost CLI is run. Projects are a top-level grouping concept but Infracost Cloud users need to filter or group cost estimates by other concepts such as departments, teams, environments... These key=value tags are also often used to slice-n-dice billing data from cloud vendors.

# Proposed solution
Enable users to set `tags` for each **project** in the `infracost.yml` [config file](https://www.infracost.io/docs/features/config_file/) running. These tags could then be used in Infracost Cloud to filter or group cost estimates. That means the tags can be used with any CI/CD integration including [GitHub App integration](https://www.infracost.io/docs/integrations/github_app/) as those read the config file.

```
version: 0.1
projects:
  - path: dev
    name: development
    terraform_var_files:
      - dev.tfvars
    tags:
      env=development
      cost-center=myTeam

  - path: prod
    name: production
    terraform_var_files:
      - dev.tfvars
    tags:
      env=production
      cost-center=myTeam
```

Thanks to @netguino for the suggestion of tagging projects instead of runs. We could also support tags on a per-run basis via CLI flags for cases when the CLI is run with one project, and the results are combined using `infracost comment` or `infracost output`.

<details>
<summary>Background info on AWS/Azure/Google tags</summary>

- [AWS](https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html):
    - The tag value must be a minimum of 0 and a maximum of 256 Unicode characters in UTF-8.
    - Allowed characters can vary by AWS service. For information about what characters you can use to tag resources in a particular AWS service, see its documentation. In general, the allowed characters are letters, numbers, spaces representable in UTF-8, and the following characters: _ . : / = + - @.
- [Azure](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources?tabs=json#limitations):
    - The tag name has a limit of 512 characters and the tag value has a limit of 256 characters. For storage accounts, the tag name has a limit of 128 characters and the tag value has a limit of 256 characters.
    - Tag names can't contain these characters: `<`, `>`, `%`, `&`, `\`, `?`, `/`
- [Google](https://cloud.google.com/resource-manager/docs/creating-managing-labels):
    - Keys have a minimum length of 1 character and a maximum length of 63 characters, and cannot be empty. Values can be empty, and have a maximum length of 63 characters.
    - Keys and values can contain only lowercase letters, numeric characters, underscores, and dashes. All characters must use UTF-8 encoding, and international characters are allowed.
</details>
