### ISSUE TITLE
Only run Infracost on changed dirs in CI/CD

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1841]
## Problem
Users with large mono repos or large number of modules find it slow to run Infracost in CI/CD since integrations like the GitHub Actions run a baseline on every dir/module, even if no TF code changed in that dir/module. One user, who switched from our Atlantis integration to GitHub Actions using HCL parsing, mentioned:
> it shouldnt be doing the baseline for everything, just for what changed...
> because Im here twiddling my thumbs...
> otherwise it works great and I am pretty happy, but the fact that it's doing ALL the repos for the baseline despite not needing them is very awful
> Specifically because the action always runs, so to wait for an extra action for 10min for a PR that didn't even touch tf code... Was though

## Proposed solution

See [this example](https://github.com/infracost/actions/tree/master/examples/using-cache) for how caching can help in GH Actions. We [discussed this](https://www.youtube.com/watch?v=mnTM3PpehZA&t=283s) in the August 2022 community call and would like to hear from the community to see if that's helping.

This will hopefully cut the time to roughly half of what it is.

### Community note
Are you using any workarounds to only run Infracost on folders that changed?

**Comment by rmgpinto** [comment]
We've extended the infracost on CircleCI to include skipping non-terraform directories:

```bash
if [ "${CIRCLE_PULL_REQUEST}" == "" ]; then
    circleci step halt
fi

GIT_LATEST_BASE_BRANCH_COMMIT=$(git log -n 1 main --pretty=format:"%H")
if [ "$(git diff-tree --no-commit-id --name-only -r ${CIRCLE_SHA1} ${GIT_LATEST_BASE_BRANCH_COMMIT} | grep -c ${TF_ROOT})" == "0" ]; then
    circleci step halt
fi
```

**Comment by jrmash** [comment]
I ran into a similar scenario with a Terragrunt project and used the [Changed Files Action](https://github.com/marketplace/actions/changed-files) to retrieve a list of directories changed in the pull request -- Something like this:

```yaml
## This is not a complete or functional example and may contain
## syntax errors, typos, or other errata. 
steps:
  - name: Fetch Changes
    id: fetch-changes
    uses: tj-actions/changed-files@v11.5
    with:
      dir_names: true
  - name: Execute Infracost Breakdown
    run: |
      for entry in ${{ steps.fetch-changes.outputs.all_changed_and_modified_files }}; do
        infracost breakdown --no-color --path "${entry}"
      done
```

The project I was working on used something derived from the above combined with the [GitHub Workflow Matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) feature to operate on all changed directories in parallel. This might be worth a look for your project(s) as well.
