### ISSUE TITLE
Infracost comment don't include per-project path breakdown

### ISSUE THREAD

**Issue by lvkins** [infracost/infracost#1882]
First of all, kudos for a great tool!

I'm having an issue presenting per-project path price breakdown. Currently, the pricing table looks as follows:  

---

💰 Infracost estimate: **monthly cost will not change**
<table>
  <thead>
    <td>Project</td>
    <td>Previous</td>
    <td>New</td>
    <td>Diff</td>
  </thead>
  <tbody>
    <tr>
      <td>All projects</td>
      <td align="right">$45</td>
      <td align="right">$45</td>
      <td>$0</td>
    </tr>
  </tbody>
</table>

3 projects have no cost estimate changes.

---

With following `infracost.yml` config:

```yml
version: 0.1

projects:
  - path: environments/common
    name: Common
  - path: environments/staging
    name: Staging
  - path: environments/production
    name: Production
```

I would expect the pricing table to have per configured project price breakdown:

---

💰 Infracost estimate: **monthly cost will not change**
<table>
  <thead>
    <td>Project</td>
    <td>Previous</td>
    <td>New</td>
    <td>Diff</td>
  </thead>
  <tbody>
    <tr>
      <td>Common</td>
      <td align="right">$5</td>
      <td align="right">$5</td>
      <td>$0</td>
    </tr>
    <tr>
      <td>Staging</td>
      <td align="right">$11</td>
      <td align="right">$11</td>
      <td>$0</td>
    </tr>
    <tr>
      <td>Production</td>
      <td align="right">$29</td>
      <td align="right">$29</td>
      <td>$0</td>
    </tr>
  </tbody>
</table>

3 projects have no cost estimate changes.

---

Is this a bug or I'm missing something? 

Thanks
