### ISSUE TITLE
breakdown produces a file that cannot be consumed with diff

### ISSUE THREAD

**Issue by orbitz** [infracost/infracost#1952]
Given a configuration file like:

```yaml
projects:
  - path: foo
  - path: foo/bar
```

The output of breakdown will have multiple entries for `foo/bar` due to the recursive nature.  But this output cannot be used with `diff` because it states there are multiple projects with the same name.

In my case, I would like to process specifically only those paths that I specify, no recursively.  I am using tooling that decides what to operate.

I tried:

```yaml
projects:
  - path: foo
    exclude_paths: [foo/*/*]
  - path: foo/bar
    exclude_paths: [foo/bar/*/*]
```

Although this did not work.

Any suggestions for how to address this?

One idea, is perhaps adding a `recursive` option to the config so I could do:

```yaml
projects:
  - path: foo
    recursive: false
  - path: foo/bar
    recursive: false
```

In the mean time, I'm not sure if it's safe for me to manipulate the output JSON to remove duplicate projects?

I could also name each project differently, but I'm not quite sure what this means for the summary information, is a directory counted twice in that case?

Thank you.

**Comment by orbitz** [comment]
Another example where this has come up is we have a repository that is really big and running infracost on it just takes a long time.  We'd like to be able to target exactly what dirs we want run at any particular time, for performance reasons, and now have infracost recursively find more directories.

**Comment by Tomasz-Kluczkowski** [comment]
I had this issue for terragrunt based project, had to completely remove the name parameter from config file and then it uses paths to modules and all works.

```yaml
version: 0.1

projects:
  - path: .
```

instead of:

```yaml
version: 0.1

projects:
  - path: .
  - name: <project name>
```
