### ISSUE TITLE
Environment variable INFRACOST_AZURE_OVERRIDE_REGION not producing effect inside config file

### ISSUE THREAD

**Issue by pacorreia** [infracost/infracost#2331]
Hi team,

Tried to implement region override for Azure using a config file like below:

```yaml
version: 0.1

projects:
  - path: src
    terraform_var_files:
      - ../vars/dev.json
      - ../tags.json
    usage_file: infracost-usage.yml
    name: development
    env:
      INFRACOST_AZURE_OVERRIDE_REGION: uksouth
```

When running a breakdown operation the result is:

> time="2023-03-06T14:14:09Z" level=warning msg="Using eastus for resource azurerm_cosmosdb_account.cosmosdb_account as its 'location' property could not be found."

Please note the location fallback to eastus rather than uksouth.

Following the suggestion of @hugorut, I've run the same breakdown but declaring the variable inline:
> INFRACOST_AZURE_OVERRIDE_REGION=uksouth infracost breakdown --config-file infracost.yml

And it worked like a charm.

Would be great to allow this kind of override inside config file, to avoid changing CI/CD pipelines, and keep it all strictly under code :)
