### ISSUE TITLE
Automatically calculate Google Sustained Use Discount from `monthly_hrs`

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#2356]
The [Infracost usage-file](https://www.infracost.io/docs/features/usage_based_resources/) supports a `monthly_hrs` parameter for Google instances as shown below. However, this value is currently not taken into account when calculating the sustained use discount that is applied to this resource. We should be able to code [this discount logic](https://cloud.google.com/compute/docs/sustained-use-discounts) into the [resource calculator](https://github.com/infracost/infracost/blob/master/internal/resources/google/compute_cost_component_helpers.go#L34) so users can specify their `monthly_hrs` and leave the calculation up to us. That's similar to what the [Google price calculator](https://cloud.google.com/products/calculator) does.

```
# main.tf

provider "google" {
 credentials = "{\"type\":\"service_account\"}"
 region      = "us-central1"
}

resource "google_compute_instance" "instance1" {
 name         = "instance1"
 machine_type = "n1-standard-32"
 zone         = "us-central1-a"
}
```

```
# infracost-usage.yml

version: 0.1
resource_type_default_usage:
  # Use this monthly_hrs as a default for all google_compute_instances
  google_compute_instance:
    monthly_hrs: 730

resource_usage:
  # Use array wildcard to override a group of instances' monthly_hrs
  mod.my_module[*].google_compute_instance[*]:
    monthly_hrs: 600

  # Override a specific instance's monthly_hrs
  google_compute_instance.instance1:
    monthly_hrs: 365
```

```
# infracost breakdown --path . --usage-file infracost-usage.yml --fields all

Project: infracost/example-terraform/google

 Name                                                       Price  Monthly Qty  Unit   Hourly Cost  Monthly Cost

 google_compute_instance.instance1
 └─ Instance usage (Linux/UNIX, on-demand, n1-standard-32)  $1.52          730  hours        $1.52       $776.72
```
