### ISSUE TITLE
Clearing Up Usage File

### ISSUE THREAD

**Issue by dulakm** [infracost/infracost#2411]
## Current state

Usage files (`--usage-file`) generated by running `--sync-usage-file` have bunch of comments that by some teams may be seen as messy. Removing these comments is not respected and running `--sync-usage-file` reintroduces them again.

Modifying some comments is respected and the change is kept. However new comments added by a programmer are deleted when running `--sync-usage-file`.

Some teams may want to write helpful comments for the rest of the team why some usage param was chosen how it was chosen. E.g.
```
  azurerm_monitor_action_group.default:
    # 1 notification per every day per every environment
    monthly_notifications: 90
```

The current setup doesn't support that.

### Not having "unnecessary comments"
I would argue that absolute majority of comments currently generated are not really useful as they just rephrase what is already visible and understandable from the name of the parameter. E.g.
```
azurerm_storage_account.application_storage:
  data_at_rest_storage_gb: 0.0 # Total size of Data at Rest in GB (File storage).
  early_deletion_gb: 0.0 # Total size of Early deletion data in GB.
  snapshots_storage_gb: 0.0 # Total size of Snapshots in GB (File storage).
  metadata_at_rest_storage_gb: 0.0 # Total size of Metadata in GB (File storage).
  storage_gb: 0.0 # Total size of storage in GB.
  ...
```
I think that having such comments lowers visiblity of useful comments and is actually against clean code standards.

### Respecting newly added comments
Examples of comments being currently deleted:
```
version: 0.1
resource_type_default_usage:
  # We set storage account usage globally as it's really cheap and we don't mind slight differences
  azurerm_storage_account:
    ...
```

```
version: 0.1
resource_type_default_usage:
  azurerm_storage_account: # We set storage account usage globally as it's really cheap and we don't mind slight differences
    ...
```

I'd be great if adding such comments would be respected and they wouldn't be deleted.

Any of the features above can be enabled only by using a special flag, however I'd personally consider them to be good practise enough to be enabled by default.
