### ISSUE TITLE
Broken PR comment report for Bitbucket Cloud

### ISSUE THREAD

**Issue by keyvanakbary** [infracost/infracost#2799]
Hi there, first, thanks a lot for this fantastic project!

I've integrated infracost in our Terraform CI and for some reason the UI markdown for comments in PRs (Bitbucket Cloud) are broken. The "Cost details" h3 is rendered within a row in the summary in plain markdown.

![image](https://github.com/infracost/infracost/assets/717129/2c66ec58-a8dc-404b-b4d2-220ab8ba8868).

I'm using the Docker image `infracost/infracost:ci-0.10` and the command I'm using to post the comment is:

    infracost comment bitbucket --path infracost.json --repo $BITBUCKET_WORKSPACE/$BITBUCKET_REPO_SLUG --pull-request $BITBUCKET_PR_ID --bitbucket-token $BITBUCKET_TOKEN --behavior update

My Bitbucket pipeline looks like the following:

```
pipelines:
  pull-requests:
    '**':
      - step:
          name: Terraform plan
          image: hashicorp/terraform:1.6.6
          script:
            - terraform init
            - terraform plan -out plan.binary
            - terraform show -json plan.binary > plan.json
          artifacts:
            - plan.json
      - step:
          name: Infracost
          image: infracost/infracost:ci-0.10
          script:
            - infracost diff --usage-file infracost-usage.yml --path plan.json --format json --out-file infracost.json
            - infracost comment bitbucket --path infracost.json --repo $BITBUCKET_WORKSPACE/$BITBUCKET_REPO_SLUG --pull-request $BITBUCKET_PR_ID --bitbucket-token $BITBUCKET_TOKEN --behavior update
```

I suspect it has to do with the markdown template.

Please let me know if I can help in any way! Thanks a lot!
