### ISSUE TITLE
I can't setup my SSH key for my private modules

### ISSUE THREAD

**Issue by thomaspicquet** [infracost/infracost#324]
Hello,

I tried a few things but I can't get my private modules to download correctly:
```
  $ infracost --no-color --tfdir terraform
time="2021-01-11T23:20:50Z" level=info msg="starting: Running terraform init"
time="2021-01-11T23:20:50Z" level=info msg="Running command: /usr/bin/terraform init -input=false -no-color"
time="2021-01-11T23:20:51Z" level=error binary=terraform
time="2021-01-11T23:20:51Z" level=error binary=terraform msg="Error: Failed to download module"
time="2021-01-11T23:20:51Z" level=error binary=terraform
time="2021-01-11T23:20:51Z" level=error binary=terraform msg="Could not download module \"codepipeline_requirements\" (main.tf:169) source"
time="2021-01-11T23:20:51Z" level=error binary=terraform msg="code from \"git@github.com:private/terraform-modules.git\": error downloading"
time="2021-01-11T23:20:51Z" level=error binary=terraform msg="'ssh://git@github.com/private/terraform-modules.git': /usr/bin/git exited"
```
Is there a way to use a custom SSH key? I tried setting up a private SSH key with a github action but its not updating the one used inside the docker image for infracost

Thanks for your help

**Comment by aliscott** [comment]
@thomaspicquet thanks, I'll look into replicating this.

Some quick questions that would help:

Do you have an example of your github action YAML?
What are you using for setting up your private SSH key with the action?
Are you using `ssh-key` and `persist-credentials` inputs here (https://github.com/actions/checkout#usage)?

**Comment by thomaspicquet** [comment]
@aliscott here's the full GH action:
```
on:
    push:
        branches:
            - master
            - development
        paths:
            - '**.tf'
            - '**.tfvars'
            - '**.tfvars.json'
jobs:
    infracost:
        runs-on: ubuntu-latest
        name: Show infracost diff
        steps:
            - uses: actions/checkout@v2
            - uses: webfactory/ssh-agent@v0.4.1
              with:
                  ssh-private-key: ${{ secrets.INFRACOST_SSH_PRIVATE_KEY }}
            - name: Run infracost diff
              uses: infracost/infracost-gh-action@master
              env:
                  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Do not change
                  TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
              with:
                  entrypoint: /scripts/ci/diff.sh # Do not change
                  tfdir: terraform

```

I'm able to fetch my repository but it seems that the infracost/infracost docker image uses its own SSH key and there's no way to easily change it

Thank you!

**Comment by aliscott** [comment]
@thomaspicquet thank you! I'm trying to reproduce this situation on my own environment just now - will let you know when I have something.

**Comment by aliscott** [comment]
@thomaspicquet thanks for your patience on this one 😄 . I've updated the docker image to support a `GIT_SSH_KEY` environment variable (https://github.com/infracost/infracost/pull/330) and tested this works with my own private modules. You can specify it in your action yaml like this:

```
  env:
    INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
    GIT_SSH_KEY: ${{secrets.INFRACOST_SSH_PRIVATE_KEY}}
```

I've pushed this to the latest docker image in Dockerhub so you can try it now. Let me know if it works for you.
