### ISSUE TITLE
docs: lack of documentation about resources inside a module (infracost-usage.yml)

### ISSUE THREAD

**Issue by mercuriete** [infracost/infracost#375]
First of all, thanks for this awesome tool.

I think there is a lack of information in the infracost-usage.yml documentation when the resource is inside a module.
I am trying to estimate the cost of a dynamodb as following:

main.tf
```
module "dynamodb_table" {
  source   = "terraform-aws-modules/dynamodb-table/aws"
  version = "0.11.0"
  name     = "${local.name_prefix}-dynamo-transactions-table"
  hash_key = "id"

  attributes = [
    {
      name = "id"
      type = "N"
    }
  ]
}

```

I want to estimate the cost of a dynamodb

result:
```
  module.dynamodb_table.aws_dynamodb_table.this[0]                                                                        
  ├─ Write request unit (WRU)                                          -  WRUs          1e-06            -             -  
  ├─ Read request unit (RRU)                                           -  RRUs          2e-07            -             -  
  ├─ Data storage                                                      -  GB-months    0.2500            -             -  
  ├─ Continuous backup storage (PITR)                                  -  GB-months    0.2000            -             -  
  ├─ On-demand backup storage                                          -  GB-months    0.1000            -             -  
  ├─ Restore data size                                                 -  GB           0.1500            -             -  
  └─ Streams read request unit (sRRU)                                  -  sRRUs         2e-07            -             -  
  Total                                                                                                  -             -  
```

infracost-usage.yml
```
version: v0.1
resource_usage:
module.dynamodb_table.aws_dynamodb_table.this[0]:
  monthly_write_request_units: 3000000  # Write request units per month in (used for on-demand DynamoDB).
  monthly_read_request_units: 8000000   # Read request units per month in (used for on-demand DynamoDB).
  storage_gb: 230                       # Total storage for tables in GB.
  pitr_backup_storage_gb: 2300          # Total storage for Point-In-Time Recovery (PITR) backups in GB.
  on_demand_backup_storage_gb: 460      # Total storage for on-demand backups in GB.
  monthly_data_restored_gb: 230         # Size of restored data per month in GB.
  monthly_streams_read_request_units: 2 # Streams read request units per month.
```

terraform plan
```
  # module.dynamodb_table.aws_dynamodb_table.this[0] will be created
  + resource "aws_dynamodb_table" "this" {
      + arn              = (known after apply)
      + billing_mode     = "PAY_PER_REQUEST"
      + hash_key         = "id"
      + id               = (known after apply)
      + name             = "CENSORED-table"
      + stream_arn       = (known after apply)
      + stream_enabled   = false
      + stream_label     = (known after apply)
      + stream_view_type = (known after apply)
      + tags             = {
          + "Name" = "CENSORED-table"
        }

      + attribute {
          + name = "id"
          + type = "N"
        }

      + point_in_time_recovery {
          + enabled = false
        }

      + server_side_encryption {
          + enabled     = false
          + kms_key_arn = (known after apply)
        }

      + timeouts {
          + create = "10m"
          + delete = "10m"
          + update = "60m"
        }

      + ttl {
          + enabled = false
        }
    }
```

**Comment by aliscott** [comment]
Thanks @mercuriete! Agree about the lack of documentation - I'll add some as part of this ticket.

We have been working to make the usage keys more consistent for the next release (in the next couple of days).

If you're using master then the keys you are using are correct.
If you're using v0.7.15 then the keys are here: https://github.com/infracost/infracost/blob/v0.7.15/infracost-usage-example.yml#L34-L43, but these will change in the next release.

The only other thing I notice is the indentation of the YAML. The module key should be indented under resource_usage like this:
```yaml
version: v0.1
resource_usage:
  module.dynamodb_table.aws_dynamodb_table.this[0]:
    monthly_write_request_units: 3000000  # Write request units per month in (used for on-demand DynamoDB).
    monthly_read_request_units: 8000000   # Read request units per month in (used for on-demand DynamoDB).
    storage_gb: 230                       # Total storage for tables in GB.
    pitr_backup_storage_gb: 2300          # Total storage for Point-In-Time Recovery (PITR) backups in GB.
    on_demand_backup_storage_gb: 460      # Total storage for on-demand backups in GB.
    monthly_data_restored_gb: 230         # Size of restored data per month in GB.
    monthly_streams_read_request_units: 2 # Streams read request units per month.
```
