### ISSUE TITLE
Add support for Google VPNs

### ISSUE THREAD

**Issue by sinabakh** [infracost/infracost#470]
Terraform resources:
`google_compute_vpn_gateway`
`google_compute_vpn_tunnel`
`google_compute_external_vpn_gateway`
`google_compute_ha_vpn_gateway`

Pricing page:
https://cloud.google.com/network-connectivity/docs/vpn/pricing

**Comment by sinabakh** [comment]
I'll work on it.

**Comment by tim775** [comment]
`google_compute_vpn_tunnel` should have `VPN Tunnel` with unit `hours`.

`google_compute_external_vpn_gateway` should have a usage parameter `monthly_egress_data_transfer_gb` with sub parameters for the three categories specified in the princg ( this is similiar to `monthly_egress_data_transfer_gb` in  `storage_bucket`):
```
    monthly_egress_data_transfer_gb:
      worldwide: 12500
      china: 50
      australia: 250
```
These should display with the following names and tiers with unit `GB`:
```
IPSec traffic to worldwide excluding Australia, China, but including Hong Kong (first 1TB)
IPSec traffic to worldwide excluding Australia, China, but including Hong Kong (next 9TB)
IPSec traffic to worldwide excluding Australia, China, but including Hong Kong (over 10TB)
IPSec traffic to China excluding Hong Kong (first 1TB)
IPSec traffic to China excluding Hong Kong (next 9TB)
IPSec traffic to China excluding Hong Kong (over 10TB)
IPSec traffic to Australia (first 1TB)
IPSec traffic to Australia (next 9TB)
IPSec traffic to Australia (over 10TB)
```

`google_compute_vpn_gateway` and `google_compute_ha_vpn_gateway` should have a usage parameter `monthly_egress_data_transfer_gb` with sub parameters for the categories specified `VM-VM egress pricing within Google Cloud`:
```
    monthly_egress_data_transfer_gb:
      same_region: 12500
      us_or_canada:
      europe:
      asia:
      south_america:
      worldwide:
      oceania:
```
These should display with the following names with unit `GB`:
```
IPSec traffic within the same region
IPSec traffic within the US or Canada
IPSec traffic within Europe
IPSec traffic within Asia
IPSec traffic within South America
IPSec traffic between continents (excludes Oceania)
IPSec traffic to/from Indonesia and Oceania 
```
