### ISSUE TITLE
Bad calculation on EC2 spot instances when are inside a managed node_group

### ISSUE THREAD

**Issue by mercuriete** [infracost/infracost#477]
Description:

When an EC2 instance group is created because they are created using aws_eks_node_group ...
If the capacity type is SPOT the calculation is done as if they were ON_DEMAND.

step to reproduce:

1. create an EKS cluster with aws_eks_cluster
2. create an EKS node_group with aws_eks_node_group
3. put  ```  capacity_type  = "ON_DEMAND"```
4. change to -> ```capacity_type  = "SPOT"```

Actual behaviour:
* infracost is calculating as on demand instances

Expected behaviour:
* Reduced prices calculating with spot cost.

output:
```
module.eks-cluster.aws_eks_node_group.node-group-spot[0]                                                                       
  ├─ Linux/UNIX usage (on-demand, t2.small)                            2,920  hours           0.0276       0.1104       80.5920  
  └─ General Purpose SSD storage (gp2)                                    20  GB-months       0.1200       0.0033        2.4000  
  Total                                                                                                    0.1137       82.9920  
```

I will try to give more information if is needed.

Thanks for this awesome product.

**Comment by alikhajeh1** [comment]
@mercuriete thanks for reporting this in a detailed way that enabled us to [fix it](https://github.com/infracost/infracost/pull/485) quickly :) It'll go out in the next release in ~1week.

**Comment by mercuriete** [comment]
thanks!!!
:+1:

**Comment by mercuriete** [comment]
@alikhajeh1 please reopen this issue:

infracost 0.8.0 reports the following:

```
 module.eks-cluster.aws_eks_node_group.node-group-spot[0]                                                         
 ├─ Linux/UNIX usage (spot, t3.small)                                     2,920  hours                     $21.61 
 ├─ CPU credits                                                           2,920  vCPU-hours               $146.00 
 └─ General Purpose SSD storage (gp2)                                        20  GB-months                  $2.40 
```

but if you go to aws -> ec2 -> spot instances -> savings summary..

this is shown:

```
Spot usage and savings

4
Spot Instances

160
vCPU-hours

160
Mem(GiB)-hours

$1.98
On-Demand total

$0.59
Spot total

70%
Savings
```

so the total is $0.59 instead of $170.01
Thanks

**Comment by mercuriete** [comment]
@alikhajeh1 please reopen this issue....

the report from infracost 0.8.0 is:

```
 module.eks-cluster.aws_eks_node_group.node-group-spot[0]                                                         
 ├─ Linux/UNIX usage (spot, t3.small)                                     2,920  hours                     $21.61 
 ├─ CPU credits                                                           2,920  vCPU-hours               $146.00 
 └─ General Purpose SSD storage (gp2)                                        20  GB-months                  $2.40 
```

but if you see what was before:

```
module.eks-cluster.aws_eks_node_group.node-group-spot[0]                                                                       
  ├─ Linux/UNIX usage (on-demand, t2.small)                            2,920  hours           0.0276       0.1104       80.5920  
  └─ General Purpose SSD storage (gp2)                                    20  GB-months       0.1200       0.0033        2.4000  
  Total                                                                                                    0.1137       82.9920  
```

the cost has increased instead of go down.
something is wrong there.

Thanks for your work.

**Comment by robh007** [comment]
@alikhajeh1 I'll take a look at this.

**Comment by robh007** [comment]
I've had a look into this and the price for the EC2 instances is correct. If you look at the two examples one uses a t2 & one uses a t3. With t3 instances CPU credits are being calculated & that's what's increasing the cost. I think the CPU credits can be calculated better. So I'll raise another issue for that & I'll reference this in the new issue. However I think this can be closed @mercuriete @alikhajeh1

**Comment by alikhajeh1** [comment]
Thanks @robh007

**Comment by mercuriete** [comment]
thanks @robh007

**Comment by alikhajeh1** [comment]
@mercuriete just FYI that as part of the v0.8.6 release these usage file params are available, the bottom two were added/updated by @robh007 as part of https://github.com/infracost/infracost/issues/554

```
  aws_eks_node_group.my_instance:
    operating_system: linux # Override the operating system of the instance, can be: linux, windows, suse, rhel.
    reserved_instance_type: standard # Offering class for Reserved Instances. Can be: convertible, standard.
    reserved_instance_term: 1_year # Term for Reserved Instances. Can be: 1_year, 3_year.
    reserved_instance_payment_option: partial_upfront # Payment option for Reserved Instances. Can be: no_upfront, partial_upfront, all_upfront.
    # Only applicable for T3 & T4 instance types or if you specify a t2 instance within a launch template.
    monthly_cpu_credit_hrs: 350 # Number of hours in the month where the instance is expected to burst.
    vcpu_count: 2 # Number of the vCPUs for the instance type.
```
