### ISSUE TITLE
Add support for Azure DNS

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#709]
Pricing details: https://azure.microsoft.com/en-us/pricing/details/dns/
Notice the bottom of the pricing page has a question with "Which Regions correspond to Zone 1, Zone 2, Zone 3, US Gov Zone 1 and Germany Zone?". All all the following resources, the `resource_group_name` param can be used to fetch the location and map that to the zone.

Terraform resources `azurerm_dns_zone` and `azurerm_private_dns_zone` should have:
- "Hosted zone", units "months"

Each of the 9 `azurerm_dns_..._record` resources, and each of the 7 `azurerm_private_dns_..._record` should have:
- "DNS queries (first 1B)", units "1M queries".
- "DNS queries (over 1B)", units "1M queries". 
Usage file params: 
```
azurerm_dns_..._record.my_..._record:
    monthly_queries: 10000

azurerm_private_dns_..._record.my_private_..._record:
    monthly_queries: 10000
```
Always show the first tier (even if monthly_queries is not present, but with cost-depends-on-usage). Only show "over 1B" if applicable. 

Free resource:
`azurerm_private_dns_zone_virtual_network_link`
