### ISSUE TITLE
Enhancement: Add support for wildcard resource usage for module arrays/maps

### ISSUE THREAD

**Issue by m-yosefpor** [infracost/infracost#874]
As of Terraform 0.13 `for_each` and `count` works with modules as well.
Currently we support `count `and `for_each` for modules in price breakdown, however the for usage based resources, some has to express the module resource usages such as:

```
resource_usage:
  module.dev[0].aws_lambda_function.hello_world:
    monthly_requests: 10000
    request_duration_ms: 10
  module.dev[1].aws_lambda_function.hello_world:
    monthly_requests: 20000
    request_duration_ms: 10
```
for resource arrays and

```
resource_usage:
  module.dev["foo"].aws_lambda_function.hello_world:
    monthly_requests: 10000
    request_duration_ms: 10
  module.dev["bar"].aws_lambda_function.hello_world:
    monthly_requests: 10000
    request_duration_ms: 10
```
for resource maps.

Currently it's not possible to define wildcard resource usage for **module** arrays/maps (although it works for **resource** arrays/maps):

```
  module.dev[*].aws_lambda_function.hello_world:
    monthly_requests: 10000
    request_duration_ms: 10
```
