### ISSUE TITLE
Terraform Cloud and GitHub Action - can't retrieve remote state

### ISSUE THREAD

**Issue by florianpialoux** [infracost/infracost#883]
I was trying to get a Github repository that contains my .tf files with your [GitHub Action](https://github.com/marketplace/actions/infracost)

It seems that Infracost is unable to grab the current state from Terraform Cloud although I've set `INFRACOST_TERRAFORM_CLOUD_TOKEN` and `INFRACOST_TERRAFORM_WORKSPACE`

**infracost.yml:**
````
on:
  pull_request:
    paths:
    - 'gcp/**.tf'
jobs:
  infracost:
    runs-on: ubuntu-latest
    name: Show infracost diff
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run infracost diff
      uses: infracost/infracost-gh-action@master
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        INFRACOST_TERRAFORM_BINARY: terraform_0.13
        INFRACOST_TERRAFORM_CLOUD_TOKEN: ${{ secrets.INFRACOST_TERRAFORM_CLOUD_TOKEN }}
        INFRACOST_TERRAFORM_WORKSPACE: gcp-stage
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      with:
        entrypoint: /scripts/ci/diff.sh # Do not change
        config_file: infracost-config-gcp.yml
````

**infracost-config-gcp.yml:**
````
version: 0.1
projects:
  - path: gcp/global
    terraform_workspace: gcp-global
  - path: gcp/prod
    terraform_workspace: gcp-prod
  - path: gcp/stage
    terraform_workspace: gcp-stage
````
It is able to generate the comment on my PR but cannot guess the cost of the previous plan.
Previous monthly cost is always set to $0
![image](https://user-images.githubusercontent.com/73372865/127237416-b8abdf10-5758-4114-bb4e-40d538b48a72.png)

A side note although it might be obvious but my workspaces hosted by Terraform Cloud are all set to remote execution mode.
Am I missing something?
