### ISSUE TITLE
Support setting env overrides in the config file

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#905]
## Problem

In the Infracost config file you can specify paths to different projects, e.g:

```yml
projects:
  - path: /path/to/dev/infra
  - path: /path/to/prod/infra
```

These projects may use different cloud credentials, so it would be good to be able to pass in different `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env variables for each project

## Proposal

* Add an `env` key to each project in the config file which can be used to override the env for that project. 
* Allow environment variables to be substituted in the YAML so we don't need to add raw credentials.

For example:

```yml
projects:
  - path: /path/to/dev/infra
    env:
      AWS_ACCESS_KEY_ID: ${DEV_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${DEV_AWS_SECRET_ACCESS_KEY}

  - path: /path/to/prod/infra
    env:
      AWS_ACCESS_KEY_ID: ${PROD_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${PROD_AWS_SECRET_ACCESS_KEY}
```
