### ISSUE TITLE
Terragrunt: add project-specific usage to usage file

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#934]
## Problem

* A single Infracost run supports outputting the results for multiple projects
* The [Infracost usage file](https://www.infracost.io/docs/usage_based_resources#infracost-usage-file) identifies resources using the Terraform address of the resource. This address is not unique across different projects.
* Projects are likely to use resources with the same address in cases where the user has a different project for dev and for prod. This is a common setup when using a tool like Terragrunt, or using Terraform workspaces. And the usage is likely to be different for dev and prod environments.

The current workaround is that users specify separate usage files for different projects using the [config file](https://www.infracost.io/docs/multi_project/config_file). But this will not work for cases where we are auto-detecting projects, like for Terragrunt (https://github.com/infracost/infracost/issues/807).

### Option A

We allow users to specify project-specific overrides in a `projects` array in the usage file. Since this is additive-only then it will be backwards compatible. Example:

```yml
version: 0.1

# Default usages
resource_usage:
  aws_lambda_function.my_function:
    request_duration_ms: 600
    
# This has any overrides/per-project usage
projects:
  - path: my/dev/project
    resource_usage:
      aws_dynamodb_table.my_table:
        storage_gb: 10

      aws_lambda_function.my_function:
        monthly_requests: 100

  - path: my/prod/project
    resource_usage:
      aws_dynamodb_table.my_table:
        storage_gb: 10000

      aws_lambda_function.my_function:
        monthly_requests: 200000
```

## Open questions

1. How does this work with `--sync-usage-file`? Initially it seems fine to keep the current logic and allow users to add manually add project-specific overrides. If users add project-specific overrides then the `--sync-usage-file` should not override them.
2. When we update `--sync-usage-file` to pull data from external resources how does the above change? If the user has multiple projects, then we would probably want to populate the project-specific usages.
3. How should we uniquely identify a project in the usage file? For Terragrunt projects the path should uniquely identify the project, but for Terraform projects you need both the path and the Terraform workspace. This may also differ in the future for other IaC tools. For example. Pulumi uses stacks for different environments.

### Note for community
Please 👍 if you'd like to upvote this or receive updates.
See our [contributing guide](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md) if you'd like to help with this issue!

**Comment by aliscott** [comment]
@xeger and @tim775 it would be great to get your thoughts on this, particularly Q1 and Q2 since this overlaps with your current investigation into how to populate the usage.

cc @sinabakh as well since you know the usage file the best.

**Comment by tim775** [comment]
Could we have multiple usage files, one for each project?  The default behavior could be that the project's usge files is named 'infracost-usage.yml' and resides at the same path as the project.  

Another benefit of this is we could 'auto-detect' the usage file, and the --usage-file flag would be come optional (only used if you want your usage file in a different place)

**Comment by xeger** [comment]
@tim775 this was my thought exactly (granted that I am very new to this project).

Logically speaking, projects are 100% separated from each other: each project uses independent credentials, deploys to different regions, and has different resources than any other project. I enjoy the fact that Infracost currently respects this separation and keeps the projects' persistent data separate.

Establishing a naming convention for usage files would make a CLI flag optional and keep projects' state separate, so it seems like a clean approach.

**Comment by sinabakh** [comment]
Based on @tim775 and @xeger comments, I also believe having a separate usage file for each project would be the best option.

**Comment by aliscott** [comment]
I like the idea of auto-detecting the `infracost-usage.yml` file. I see how this would work in the future for Terraform mono-repos and Terragrunt projects. The main issue I see is how it could work if we auto-detect Terraform workspaces (as per https://github.com/infracost/infracost/issues/490) since these workspaces all live in the same directory

**Comment by aliscott** [comment]
> If IC were using an infracost config file to interface a multi-workspace TF project, how would that look? I'd be able to specify a bunch of projects, all happening to have the same root, and I'd specify a different usage file name for each project -- probably infracost-usage-X.yml with X being a workspace name.

Exactly, currently you can do this with an infracost config file like this:
```yml
version: 0.1

projects:
  - path: examples/terraform
    terraform_workspace: prod
    usage_file: infracost-usage-prod.yml

  - path: examples/terraform
    terraform_workspace: dev
    usage_file: infracost-usage-dev.yml
```

> My mental model of auto-discovery is that it's writing a virtual config file for you -- specifying your projects and their parameters. Don't know if that's a realistic simplification, but I'll assume so for a moment.

This is how I view it as well. We have thought about having discovery populating the config file as a separate step, but this seems like overhead for the user so I'm not sure.
