### ISSUE TITLE
Can't run with Terraform Cloud with prefix mode

### ISSUE THREAD

**Issue by alex-3sr** [infracost/infracost#943]
Hi All,

I'm trying since this morning to start working infracost in Azure DevOps PR by using Terraform Cloud.
I encounter 2 difficulties during this configuration.

First, even by set **INFRACOST_TERRAFORM_CLOUD_TOKEN** with the correct token, it always need a **.terraformrc** file
```
Running infracost breakdown using:
  $ infracost breakdown --no-color --format json --path /home/vsts/work/1/s/Terraform
time="2021-09-06T16:27:34Z" level=info msg="Detected Terraform directory at /home/vsts/work/1/s/Terraform"
time="2021-09-06T16:27:34Z" level=debug msg="Checking if /home/vsts/work/1/s/Terraform is a git repo"
time="2021-09-06T16:27:34Z" level=debug msg="Creating temporary config file for Terraform credentials"
time="2021-09-06T16:27:34Z" level=debug msg="TF_CLI_CONFIG_FILE is set, copying existing config from .terraformrc to config to temporary config file /tmp/824491119"
Error: open /home/vsts/work/1/s/Terraform/.terraformrc: no such file or directory
##[error]Bash exited with code '1'.
```

The workaround is to set a task before for write a .terraformrc file like for example 
```yaml
- bash: |
    cat << EOF >> .terraformrc
    credentials "app.terraform.io" {
      token = "$(tf_token)"
    }
    EOF
  displayName: Write Terraform.rc file
  workingDirectory: $(System.DefaultWorkingDirectory)/$(tf_path)
```

I think that using **INFRACOST_TERRAFORM_CLOUD_TOKEN**, it could be enough and able to write .terraformrc if needed really, no  ?

BTW, now that I can go on and have a workaround, it seem that it doesn't like my backend configuration and got this error ->
```
Running infracost breakdown using:
  $ infracost breakdown --no-color --format json --path /home/vsts/work/1/s/Terraform
time="2021-09-06T16:39:21Z" level=info msg="Detected Terraform directory at /home/vsts/work/1/s/Terraform"
time="2021-09-06T16:39:21Z" level=debug msg="Checking if /home/vsts/work/1/s/Terraform is a git repo"
time="2021-09-06T16:39:21Z" level=debug msg="Creating temporary config file for Terraform credentials"
time="2021-09-06T16:39:21Z" level=debug msg="TF_CLI_CONFIG_FILE is set, copying existing config from .terraformrc to config to temporary config file /tmp/034790990"
time="2021-09-06T16:39:21Z" level=debug msg="Writing Terraform credentials to temporary config file /tmp/034790990"
time="2021-09-06T16:39:21Z" level=info msg="starting: Running terraform plan"
time="2021-09-06T16:39:21Z" level=info msg="Running command: /usr/bin/terraform plan -input=false -lock=false -no-color -out=/tmp/tfplan442482005"
time="2021-09-06T16:39:23Z" level=debug binary=terraform
time="2021-09-06T16:39:23Z" level=debug binary=terraform msg="Error: error starting operation: The configured \"remote\" backend encountered an unexpected error:"
time="2021-09-06T16:39:23Z" level=debug binary=terraform
time="2021-09-06T16:39:23Z" level=debug binary=terraform msg="invalid value for workspace"
time="2021-09-06T16:39:23Z" level=debug binary=terraform

  Terraform command failed with:
    Error: error starting operation: The configured "remote" backend encountered an unexpected error:
    invalid value for workspace

Error: Error running terraform plan: exit status 1
##[error]Bash exited with code '1'.
```

On my config, I tried to use **INFRACOST_TERRAFORM_WORKSPACE** with only environnement like "PROD" or full workspace name "PROJECT-PROD", in both case I've same error. My backend configuration is like this ->
```hcl
terraform {
  required_version = "~> 1.0.3"
  required_providers {
    azurerm = {
      version = "~> 2"
      source  = "hashicorp/azurerm"
    }
  }
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "ORG"
    workspaces {
      prefix = "PROJECTXX-"
    }
  }
}
```

It's like the prefix mode in workspace is not accepted, only name is accepted. Does I'm correct ?
Here my task on Azure DevOps ->
```yaml
- bash: |
    sudo apt-get update -qq && sudo apt-get -qq install bc curl git
    curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz -C /tmp
    sudo mv /tmp/infracost-linux-amd64 /usr/bin/infracost
    curl -sL -o infracost_diff.sh https://raw.githubusercontent.com/infracost/infracost/master/scripts/ci/diff.sh
    chmod +x infracost_diff.sh
    ./infracost_diff.sh
  displayName: Run Infracost diff
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    INFRACOST_API_KEY: <xxxxx>
    INFRACOST_TERRAFORM_BINARY: /usr/bin/terraform
    INFRACOST_TERRAFORM_WORKSPACE: PROD
    INFRACOST_TERRAFORM_CLOUD_TOKEN: $(tf_token)
    INFRACOST_LOG_LEVEL: debug
    ARM_CLIENT_SECRET: <xxxxx>
    ARM_SUBSCRIPTION_ID: <xxxxx>
    ARM_TENANT_ID: <xxxxx>
    path: $(System.DefaultWorkingDirectory)/$(tf_path)
```

Thanks and remain at your disposal
Regards
Alexandre

**Comment by aliscott** [comment]
Thanks for the detailed issue @alex-3sr 🙌 . I'll break this comment down into the two issues.

**Issue 1:** `INFRACOST_TERRAFORM_CLOUD_TOKEN` not working

Out existing logic for the `INFRACOST_TERRAFORM_CLOUD_TOKEN` is to create a temporary `.terraformrc` and write the token to that file. However, if the `TF_CLI_CONFIG_FILE` env variable is already set then we try and copy that file to a temp file and overwrite the token. From what I can tell the issue here is that the `TF_CLI_CONFIG_FILE` env variable is already set, but the path it is set to doesn't exist (`/home/vsts/work/1/s/Terraform/.terraformrc`) so we are failing to copy it.

Are you able to `echo $TF_CLI_CONFIG_FILE` to validate this? If so, do you know what is setting this variable.

One fix from our end is to just log an error if we can't copy the existing file instead of a hard failure. I think this would resolve your use-case, what do you think?

**Issue 2:** `INFRACOST_TERRAFORM_WORKSPACE` not working

I was able to reproduce this and it looks like a bug with the `INFRACOST_TERRAFORM_WORKSPACE` being overwritten. I've pushed a fix in #946 so it should be in the next release.

In the meantime one of the following should work as a workaround:
1. Set `TF_WORKSPACE: PROD` env variable
2. Add the `terraform_workspace: PROD` variable (https://github.com/infracost/infracost-azure-devops/#terraform_workspace) to your Azure DevOps env.

Let me know if this works for you.

**Comment by alex-3sr** [comment]
Hi @aliscott 

Thank for your prompt response and help about my issues.

So, about the 1st point I debug ouput the `TF_CLI_CONFIG_FILE` and very surprising to get that as response : `.terraformrc`
I've no idea who can set this env variable, but OK I've a point to start diving and will find why soon.

For the 2nd point, I did the easy way by setting all variables in once. I'm sure that I've some extra one, but at least for go on debugging and find a woarkaround at least on first time. So i did a task like this -->
```yaml
- bash: |
    sudo apt-get update -qq && sudo apt-get -qq install bc curl git
    curl -sL https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz -C /tmp
    sudo mv /tmp/infracost-linux-amd64 /usr/bin/infracost
    curl -sL -o infracost_diff.sh https://raw.githubusercontent.com/infracost/infracost/master/scripts/ci/diff.sh
    chmod +x infracost_diff.sh
    ./infracost_diff.sh
  displayName: Run Infracost diff
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    INFRACOST_API_KEY: xxxx
    INFRACOST_TERRAFORM_BINARY: /usr/bin/terraform
    INFRACOST_TERRAFORM_WORKSPACE: $(target_env)
    TF_WORKSPACE: PROD
    terraform_workspace: PROD
    INFRACOST_TERRAFORM_CLOUD_TOKEN: $(tf_token)
    INFRACOST_LOG_LEVEL: debug
    path: $(System.DefaultWorkingDirectory)/$(tf_path)
```

And, boum that's works better now and didn't have anymore, but now I've errors about my tfvars. but it's discussed here : https://github.com/infracost/infracost/issues/20 So I think that I will found the way to add my tfvars as env variables I hope.

I'll refresh this thread later after more improved tests

Thanls again
Regards
Alex
