### ISSUE TITLE
How do I override the infracost command when running on GitLab (CI/CD) ?

### ISSUE THREAD

**Issue by jimsmith** [infracost/infracost#953]
Scenario using GitLab and not always wanting merge requests and we want to see the output in the pipeline itself

Need the ability to override the infracost command that gets ran when in the pipeline and also need the ability to save the format as html and upload as an artifact.

This is what happens when there's **no** merge requests but also happens when there **is a merge request** -> notice the message `404 Project Not Found`

Also when attempting to get infracost_breakdown.json there is no such file

```
Uploading artifacts...
WARNING: /builds/REDACTED/REDACTED/terraform/infracost_breakdown.json: no matching files 
ERROR: No files to upload                          
Uploading artifacts...
WARNING: /builds/REDACTED/REDACTED/terraform/infracost_breakdown.json: no matching files 
ERROR: No files to upload                          
Cleaning up file based variables
```

```
$ /scripts/ci/diff.sh
Running infracost breakdown using:
  $ infracost breakdown --no-color --format json --path /builds/REDACTED/REDACTED/terraform/ --terraform-plan-flags "-var-file=${CI_PROJECT_DIR}/terraform/environments/aws/REDACTED/${REGION}/REDACTED.tfvars"
Running infracost output using:
  $ infracost output --no-color --format diff --path infracost_breakdown.json
Posting comment as post_condition is set to always
Posting comment to GitLab commit ebcca2edf6bea999b796e0f3c08317a66dfe9b2b
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2001  100    35  100  1966    204  11462 --:--:-- --:--:-- --:--:-- 11701
{"message":"404 Project Not Found"}$
```

Oh and not able to use your GitLab template as it does not have support for GitLab's Terraform State Management (HTTP backend state stored inside GitLab)

```
.infracost:
  stage: infracost
  extends:
  image:
    name: infracost/infracost:latest
    entrypoint: [""]
  variables:
    AWS_DEFAULT_REGION: eu-west-2
    AWS_ACCESS_KEY_ID: MASKED
    AWS_SECRET_ACCESS_KEY: MASKED
    format: html > infracost_project.html   # Does this even give me a format in HTML ?
    INFRACOST_LOG_LEVEL: "warn"
    post_condition: '{"always": true}'
    path: "${CI_PROJECT_DIR}/terraform/"
    terraform_plan_flags: "-var-file=${TF_VARS_FILE}"
  before_script:
  - export DEBUG_OUTPUT=false
  - cd ${TF_ROOT}
  - terraform init -backend-config=address="${TF_ADDRESS}"
    -backend-config=lock_address="${TF_ADDRESS}/lock"
    -backend-config=unlock_address="${TF_ADDRESS}/lock"
    -backend-config=username="gitlab-ci-token"
    -backend-config=password="${CI_JOB_TOKEN}"
    -backend-config=lock_method="POST"
    -backend-config=unlock_method="DELETE"
    -backend-config=retry_wait_min="5" -reconfigure
  script:
    - "/scripts/ci/diff.sh" # Do not change
    - ls -la
  artifacts:
    reports:
      junit: ${TF_ROOT}/infracost_breakdown.json
    paths:
      - ${TF_ROOT}/infracost_breakdown.json


infracost:
  extends: .infracost
  stage: infracost
```

**Comment by aliscott** [comment]
Thanks for the detailed issue @jimsmith 🙌 . I've broken it down into three issues below.

**Issue 1:** Override infracost command and save assets

I've created proposal PR (https://github.com/infracost/infracost/pull/954) that keeps JSON the HTML assets at the end of the diff.sh run, so you can use them in a GitLab like:

```yml
.infracost:
  image:
    name: infracost/infracost:953-test
    entrypoint: [""]
  ...
  artifacts:
    paths:
      - infracost_breakdown.json
      - infracost_breakdown.html
```

I've pushed a temporary docker image that contains this to `infracost/infracost:953-test`. Can you give this a shot and let us know if that solves your use case? We can then work out if that is the default behaviour or we create an option for this.

Is there any other part of the Infracost command you need to override? You can do this currently by extending the Docker image and adding a custom `diff.sh` script, but I think it would be easier for us to add certain customizations.

**Issue 2:** 404 Project not found

I'm not able to reproduce this. The curl we make in the diff.sh script (https://github.com/infracost/infracost/blob/master/scripts/ci/diff.sh#L162-L168) is
```
curl -L -X POST -d @- \
    -H "Content-Type: application/json" \
    -H "PRIVATE-TOKEN: $GITLAB_TOKEN" \
    "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHA/comments"
```

The env variables here are [predefined by the GitLab CI](https://docs.gitlab.com/ee/ci/variables/#list-all-environment-variables). Can you try adding a task to output them so we can validate they are correct?

**Issue 3:** Support GitLab's Terraform State Management

Would supporting a `terraform_init_flags` option here (similar to `terraform_plan_flags`) help or do you have a different suggestion?
