### ISSUE TITLE
Add a Codefresh integration

### ISSUE THREAD

**Issue by userbradley** [infracost/infracost#975]
Hey there!

A lot of us (Me) use codefresh for CI, and I didn't see one for codefresh!

Let me know if you need additional details! 

### Notes for community
Please 👍 if you'd like to upvote this or receive updates.
Read the [contributing guide](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md) if you'd like to work on this issue - we're happy to help you!

**Comment by alikhajeh1** [comment]
Hi @userbradley - thanks for creating this issue! I haven't used Codefresh before, does it support adding pipeline tasks via docker images? If so, it should be easy'ish to add an integration similar to the [GitLab CI Template](https://gitlab.com/infracost/infracost-gitlab-ci/-/blob/master/infracost.yml) that uses our [diff.sh script](https://github.com/infracost/infracost/blob/master/scripts/ci/diff.sh). Do you use Codefresh with github or another VCS? I'm wondering if the pull request comment is needed or if Codefresh users are used to viewing the Codefresh dashboard to see task statuses/outputs?

**Comment by userbradley** [comment]
Hey @alikhajeh1!

As far as I understand, it does! 

I use codefresh with Github, but it supports most VCS systems (Bit bucket, gitlab (ce and cloud), github etc)

So it's a mix of both to be honest, some times we check the status dashboard to see if things have run or not, and sometimes it's nice to have it in to git it's self:

Below is an example terraform apply I botched togethet:

```
version: '1.0'
stages:
  - checkout
  - deploy
steps:
  main_clone:
    title: Git clone
    image: alpine/git:latest
    stage: checkout
    commands:
      - mkdir -p ~/.ssh
      - echo "${SSH_KEY}" | base64 -d > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan github.com > ~/.ssh/known_hosts
      - rm -rvf *dns*
      - git clone git@github.com:userbradley/tfnds.git
      - mv tfdns/* .
  DeployWithTerraform:
    image: hashicorp/terraform:light
    title: Deploying Terraform plan
    stage: deploy
    commands:
      - mkdir -p ~/.ssh
      - echo "${SSH_KEY}" | base64 -d > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan github.com > ~/.ssh/known_hosts
      - terraform init -backend-config="token="$token""
      - export TF_VAR_cloudflare_email="${CLOUDFLARE_EMAIL}"
      - export TF_VAR_cloudflare_api_key="${CLOUDFLARE_API_KEY}"
      - terraform apply -auto-approve
  ```

They have pre-built steps that you can use, so may be worth making one:
https://github.com/codefresh-io/plugins/blob/master/CONTRIBUTING.md

Let me know if you need additional details or I've not answered something
